# This is a basic workflow to help you get started with Actions

name: 爬取API信息

on: 
  release:
    types: [published]
  repository_dispatch:
  schedule:
    - cron: "0 0-15/1 * * *"
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python #安装python
        uses: actions/setup-python@v1

      - name: 安装依赖
        run: |
          pip install requests

      # Runs a set of commands using the runners shell
      - name: 爬取
        run: |
          python get.py
          sed -i '1d' issues-api.json
          sed -i '$d' issues-api.json
