# This is a basic workflow to help you get started with Actions

name: 爬取API信息

on: 
  release:
    types: [published]
  repository_dispatch:
  schedule:
    - cron: "0 0-15/1 * * *"
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python #安装python
        uses: actions/setup-python@v1

      - name: 安装依赖
        run: |
          pip install requests

      # Runs a set of commands using the runners shell
      - name: 爬取
        env:
          TOKEN: ${{ secrets.MYTOKEN }}
        run: |
          sed -i '5i ' + ''Authorization': ' + '$TOKEN', get.py
          python get.py
          sed -i '1d' issues-api.json
          sed -i '$d' issues-api.json
          
      - name: Commit
        run: |
          git config --global user.email AutoWakeUp@email.com
          git config --global user.name AutoWakeUp
          git add .
          git commit -m "Successfully Wake" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
